name: continuous integration

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: windows-latest
            py: "3.11"
          - os: macos-latest
            py: "3.11"
          - os: ubuntu-latest
            py: "3.11"
          - os: ubuntu-latest
            py: "3.10"
          - os: ubuntu-latest
            py: "3.9"
    uses: mhils/workflows/.github/workflows/python-tox.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.py }}

  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
        py:
          - "3.11"
          - "3.10"
          - "3.9"
    uses: mhils/workflows/.github/workflows/python-build.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.py }}

  check:
    if: always()
    needs:
    - test
    - build
    uses: mhils/workflows/.github/workflows/alls-green.yml@main
    with:
      jobs: ${{ toJSON(needs) }}

  deploy:
    needs: check
    uses: mhils/workflows/.github/workflows/python-deploy.yml@main
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    secrets:
      password: ${{ secrets.PYPI_TOKEN }}
